name: Rust

on: 
  push:
    branches: 
      - master

jobs:
  build_linux:
    name: linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --release --verbose
#     - name: Run tests
#       run: cargo test --verbose
  build_osx:
    name: osx
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --release --verbose
#     - name: Run tests
#       run: cargo test --verbose
  build_win32:
    name: win32
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --release --verbose
#     - name: Run tests
#       run: cargo test --verbose
